### ISSUE TITLE
arm64 support on macos

### ISSUE THREAD

**Issue by bdhoine** [rancher-sandbox/lima-and-qemu#10]
Currently I'm checking out to contribute with the patches needed to get Rancher Desktop running on Apple Silicon. In order to achieve this we need to provide binaries for lima and qemu. At the moment github actions does not provide arm64 to run builds so I'm not able to open a PR here, how should we resolve this? It looks like this is the last dependency to get a minimal working Rancher Desktop on Apple Silicon.

**Comment by jandubois** [comment]
I'm was already planning to build this manually later this week, to maybe get some Franken-build working, where the Electron GUI would run in x86_64 mode via Rosetta, but lima-and-qemu would be aarch64 binaries.

It will also require some small changes in Rancher Desktop itself to set the `arch` field correctly in `lima.yaml`, but I hope that will work out.

Of course this would only be a stop-gap thing until we can get proper builds working.

**Comment by bdhoine** [comment]
ok cool, I already fixed some hard coded arch stuff in the rancher desktop codebase and as far as I can tell it's working to boot the lima vm, I did not do any changes in the lima-config.yaml. As workaround I copied the limactl binary from the brew installed path.

```
diff --git a/scripts/download/lima.mjs b/scripts/download/lima.mjs
index 64e0514..4d56860 100644
--- a/scripts/download/lima.mjs
+++ b/scripts/download/lima.mjs
@@ -41,7 +41,8 @@ async function getLima(platform) {
 }
 
 async function getAlpineLima() {
-  const url = `${ alpineLimaRepo }/releases/download/${ alpineLimaTag }/alpine-lima-${ alpineLimaEdition }-${ alpineLimaVersion }-x86_64.iso`;
+  const arch = os.arch() == 'arm64' ? 'aarch64' : 'x86_64';
+  const url = `${ alpineLimaRepo }/releases/download/${ alpineLimaTag }/alpine-lima-${ alpineLimaEdition }-${ alpineLimaVersion }-${arch}.iso`;
   const destPath = path.join(process.cwd(), 'resources', os.platform(), `alpine-lima-${ alpineLimaTag }-${ alpineLimaEdition }-${ alpineLimaVersion }.iso`);
   const expectedChecksum = (await getResource(`${ url }.sha512sum`)).split(/\s+/)[0];
 
diff --git a/src/k8s-engine/lima.ts b/src/k8s-engine/lima.ts
index 9bd612b..9eaa563 100644
--- a/src/k8s-engine/lima.ts
+++ b/src/k8s-engine/lima.ts
@@ -48,7 +48,7 @@ type LimaConfiguration = {
   arch?: 'x86_64' | 'aarch64';
   images: {
     location: string;
-    arch?: 'x86_64';
+    arch?: 'x86_64' | 'aarch64';
     digest?: string;
   }[];
   cpus?: number;
@@ -420,7 +420,7 @@ export default class LimaBackend extends events.EventEmitter implements K8s.Kube
     const config: LimaConfiguration = merge({}, baseConfig, DEFAULT_CONFIG as LimaConfiguration, {
       images: [{
         location: this.baseDiskImage,
-        arch:     'x86_64',
+        arch:     os.arch() == 'arm64' ? 'aarch64' : 'x86_64',
       }],
       cpus:   this.cfg?.numberCPUs || 4,
       memory: (this.cfg?.memoryInGB || 4) * 1024 * 1024 * 1024,
```

**Comment by bdhoine** [comment]
not sure if this helps but I ran the build steps on my local machine (had to patch some files)

```
diff --git a/bin/appdir-lima-and-qemu.sh b/bin/appdir-lima-and-qemu.sh
index af80486..a8ede8c 100755
--- a/bin/appdir-lima-and-qemu.sh
+++ b/bin/appdir-lima-and-qemu.sh
@@ -14,7 +14,7 @@ function keepListedFiles {
   local list=$2
 
   [ -d "${dir}" ] || error "${dir} is not a directory"
   for it in $(ls ${dir}); do
     if [[ "${list}" =~ \ ${it}\  ]]; then
       continue
@@ -65,9 +65,6 @@ done
 # strip docs
 rm -rf "${appDir}/share/doc"
 
-# remove lima agent for aarch64
-rm "${appDir}/share/lima/lima-guestagent.Linux-aarch64" 
-
 # remove qemu icons, includes, etc.
 # We could fine tune the firmaware files
 rm -rf "${appDir}/include"
diff --git a/bin/lima-and-qemu.pl b/bin/lima-and-qemu.pl
index 10cc7f8..6be7350 100755
--- a/bin/lima-and-qemu.pl
+++ b/bin/lima-and-qemu.pl
@@ -30,10 +30,11 @@ use FindBin qw();
 # It shows the following binaries from /usr/local are called:
 
 my %deps;
-my $install_dir = "/usr/local";
+my $install_dir = "/opt/homebrew";
 record("$install_dir/bin/limactl");
 record("$install_dir/bin/qemu-img");
 record("$install_dir/bin/qemu-system-x86_64");
+record("$install_dir/bin/qemu-system-aarch64");

```

http://byteshark.be/rancher-desktop/lima-and-qemu.macos-arm64.tar.gz
http://byteshark.be/rancher-desktop/lima-and-qemu.macos-arm64.tar.gz.sha512sum

**Comment by bdhoine** [comment]
when testing with the attached binaries I'm getting errors so you can ignore this, closing the issue as it is on the planning to create the packaged binaries

**Comment by jandubois** [comment]
> not sure if this helps but I ran the build steps on my local machine (had to patch some files)

The `appdir-lima-and-qemu` script is actually for Linux; the `lima-and-qemu` script is for macOS.

Working on it right now. The script uses `opensnoop` probes (from `dtrace`), and those seem to be completely disabled on M1 unless you disable SIP... Thankfully you can disable SIP just for `dtrace` but leave other protections in place, but this means it will probably never run on public Github runners.

**Comment by bdhoine** [comment]
I did run the perl script indeed, also needed to disable SIP to run so no hope indeed for hosted CI/CD :( happy to hear you are working on it! Thanks for the update.
